### TENANT1
GET http://localhost:8080/clientsByDatabase
Content-Type: application/json
Accept: application/json
X-Tenant-ID: TENANT1

### TENANT2
GET http://localhost:8080/clientsByDatabase
Content-Type: application/json
Accept: application/json
X-Tenant-ID: TENANT2

### TENANT3
GET http://localhost:8080/clientsByDatabase
Content-Type: application/json
Accept: application/json
X-Tenant-ID: TENANT3



### TENANT1
POST http://localhost:8080/clientsByDatabase
Content-Type: application/json
Accept: application/json
X-Tenant-ID: TENANT1

{
  "name": "TENANT1 {{$random.uuid}}"
}

### TENANT2
POST http://localhost:8080/clientsByDatabase
Content-Type: application/json
Accept: application/json
X-Tenant-ID: TENANT2

{
  "name": "TENANT2 {{$random.uuid}}"
}

### TENANT3
POST http://localhost:8080/clientsByDatabase
Content-Type: application/json
Accept: application/json
X-Tenant-ID: TENANT3

{
  "name": "TENANT3 {{$random.uuid}}"
}